"""add EditLog

Revision ID: 36a7ddc71eb7
Revises: 48a1a56d4f42
Create Date: 2025-07-01 22:27:09.650114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a7ddc71eb7'
down_revision = '48a1a56d4f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_username', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edit_logs')
    # ### end Alembic commands ###
